<?php 
	$_products = $this->getProductCollection(); 
	if(Mage::registry('current_category')){
    	  $_products->addUrlRewrite(Mage::registry('current_category')->getId());}	
?>

<?php if ($_products->getSize()): ?>

<div class="widget em-widget-featured-products-grid">
    <div class="widget-title">
        <h2><?php echo $this->__('Feature Product'); ?></h2>
    </div>
    <div class="widget-products" id="featured_arrivals">
        <ul class="products-grid">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
     <?php 
                //$pId= $_product['entity_id']; 
                //$_product = Mage::getModel('catalog/product')->load($pId);
            ?> 
            <li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
				<?php Mage::helper('productlabels')->display($_product);?>
				
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                <div class="product-shop">
                    <div class="f-fix">
                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                        <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php //echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>
						<!--div class="actions">
						  <?php //if ($_product->isSaleable()): ?>
								<button type="button" title="<?php //echo $this->__('Add To Cart') ?>" class="button btn-cart" onclick="setLocation('<?php //echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php //echo $this->__('Add To Cart') ?></span></span></button>
							<?php //else: ?>
								<p class="availability out-of-stock"><span><?php //echo $this->__('Out of stock') ?></span></p>
							<?php //endif; ?>
							<ul class="add-to-links">
								<?php //if ($this->helper('wishlist')->isAllow()) : ?>
									<li>
										<span class="separator">+</span>
										<a href="<?php //echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php //echo $this->__('Add to Wishlist') ?></a>
									</li>
								<?php //endif; ?>
								<li><span class="separator">+</span><a href="<?php //echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="i-send-friend"><i></i><?php //echo $this->__('Email to Friend') ?></a></li>
								
							</ul>
						</div-->
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
