<?php
	$helper = Mage::helper('cms');
    $processor = $helper->getBlockTemplateProcessor();
	$idJs = "slide_".md5(uniqid(rand()));
	$classJsUl = $idJs."-ul";
	
	# option cho phép user chỉ ra unique Id của slider này, dùng cho việc khởi tạo lại khi cần ở các widget khác.
	if ($this->getData('slider_unique_id'))
		$idJs = $this->getData('slider_unique_id');	
?>
<div id="<?php echo $idJs;?>" class="slider_container<?php if($cssClass = $this->getData('css_class')):?> <?php echo $cssClass;?><?php endif;?>">
	<?php echo $processor->filter($this->getWidgetInstance());?>
	<div id="<?php echo $idJs;?>_css"></div>
</div>
<script type="text/javascript">
function em_slider_init_widget_<?php echo $idJs ?>(){
	if(jQuery('#<?php echo $idJs;?> <?php echo $this->getData('container')?>').length){
		var maxHeight = 0;
		jQuery('.item', '#<?php echo $idJs;?> <?php echo $this->getData('container')?>').each(function() {
			maxHeight = Math.max(maxHeight, jQuery(this).height());
		});
		
		var width_<?php echo $idJs;?> = jQuery('#<?php echo $idJs;?> <?php echo $this->getData('container')?> li.item').width();
		var height_<?php echo $idJs;?> = jQuery('#<?php echo $idJs;?> <?php echo $this->getData('container')?> li.item').height();
		jQuery('#<?php echo $idJs;?>_css').html('<style type="text/css">#<?php echo $idJs;?> .jcarousel-skin-tango .jcarousel-item {width:' + width_<?php echo $idJs;?> + 'px;height:' + maxHeight + 'px;}</style>');
	
		function carouselCallBack_<?php echo $idJs;?>(carousel){
		    jQuery('.<?php echo $classJsUl?>').touchwipe({
			    wipeLeft: function() { 
		    		carousel.next();
		    	},
			    wipeRight: function() { 
		    		carousel.prev();
		    	},
				preventDefaultEvents: false
			});
		}
		
		
		// khởi tạo slider 
		jQuery('#<?php echo $idJs;?> <?php echo $this->getData("container")?>')
		.addClass('<?php echo $classJsUl?>')
		.addClass('jcarousel-skin-tango')
		.jcarousel({
			<?php if ($this->getData('circular')): ?>
			wrap: 'circular',
			<?php endif ?>
			auto:<?php echo ($auto = $this->getData('auto_sliding')) ? $auto : 0;?>,
			buttonNextHTML:'<a class="next" href="javascript:void(0);" title="Next"></a>',
			buttonPrevHTML:'<a class="previous" href="javascript:void(0);" title="Previous"></a>',
			scroll:<?php echo ($scroll = $this->getData('items_per_slide')) ? $scroll : 1;?>,
			animation:'slow',
			initCallback: carouselCallBack_<?php echo $idJs;?>,
			vertical:<?php echo intval($this->getData('direction'));?>
		});
		
		
		
		<?php if ($w = $this->getSliderWidth()): ?>
			jQuery('#<?php echo $idJs;?> .jcarousel-clip').css({width:'<?php echo $w ?>px'});
		<?php endif ?>
		<?php if ($h = $this->getSliderHeight()): ?>
			jQuery('#<?php echo $idJs;?> .jcarousel-clip').css({height:'<?php echo $h ?>px'});
		<?php elseif($this->getData('direction')==1): ?>		
			jQuery('#<?php echo $idJs;?> .jcarousel-clip').css({height: maxHeight + 'px'});
		<?php endif ?>
	}
}

jQuery(document).ready(function($) {
	em_slider_init_widget_<?php echo $idJs ?>();
});
</script>