<?php
/**
 * Template for filter items block
 *
 * @var $this Mage_Catalog_Block_Layer_Filter_Abstract
 */
$_limit = (int) Mage::getStoreConfig('bubble_layer/general/items_limit');
?>
<ol>
    <?php foreach ($this->getItems() as $_i => $_item): ?>
        <?php
            $_selected  = $_item->isSelected();
            $_url       = $_selected ? $_item->getRemoveUrl() : $_item->getUrl();
            $_img       = $_item->getIcon();
            $_class     = array();
            if ($_selected) $_class[] = 'active';
            if ($_limit && $_i >= $_limit && !$_selected) $_class[] = 'hideable no-display';
        ?>
        <li class="<?php echo implode(' ', $_class) ?>">
            <?php if ($this->helper('bubble_layer')->isFilterMultiple($_item->getFilter())): ?>
                <?php $_id  = $_item->getFilter()->getRequestVar() . '-' . $_item->getValue(); ?>
                <input id="<?php echo $_id ?>"
                       type="checkbox"
                       name="<?php echo $_item->getFilter()->getRequestVar() ?>[]"
                       value="<?php echo $_url ?>"
                    <?php echo $_selected ? ' checked="checked"' : '' ?>
                       class="checkbox-filter" />
                <?php $_img = $_item->getIcon(); ?>
                <?php if ($_img): ?>
                    <img src="<?php echo $this->escapeHtml($_img); ?>" alt="" />
                <?php endif; ?>
                <label for="<?php echo $_id ?>">
                    <?php if ($_selected || !$_item->getCount()): ?>
                        <span><?php echo $_item->getLabel() ?></span>
                    <?php else: ?>
                        <a href="<?php echo $_url ?>"><?php echo $_item->getLabel() ?></a>
                    <?php endif; ?>
                </label>
            <?php elseif (!$_item->getCount()): ?>
                <?php if ($_img): ?>
                    <img src="<?php echo $this->escapeHtml($_img); ?>" alt="" />
                <?php endif; ?>
                <span><?php echo $_item->getLabel() ?></span>
            <?php else: ?>
                <?php if ($_img): ?>
                    <img src="<?php echo $this->escapeHtml($_img); ?>" alt="" />
                <?php endif; ?>
                <a href="<?php echo $_url ?>"><?php echo $_item->getLabel() ?></a>
            <?php endif; ?>
            <?php if ($this->shouldDisplayProductCount()): ?>
                (<?php echo $_item->getCount() ?>)
            <?php endif; ?>
        </li>
    <?php endforeach ?>
    <?php if ($_limit && isset($_i) && $_i > $_limit): ?>
        <li class="a-right"><a href="#" class="show-hidden"><?php echo $this->__('Show More') ?></a></li>
        <li class="a-right"><a href="#" class="show-hidden no-display"><?php echo $this->__('Show Less') ?></a></li>
    <?php endif; ?>
</ol>