<?php
/**
 * @var $this Bubble_Layer_Block_Catalog_Layer_Js
 */
?>
<script type="text/javascript">
//<![CDATA[
var BubbleLayer = new BubbleLayer({
    enableAjax: <?php echo $this->getAjaxEnabled(); ?>,
    enableAutoScroll: <?php echo $this->getAutoScrollEnabled(); ?>,
    currentUrl: '<?php echo $this->helper('core/url')->getCurrentUrl() ?>',
    priceFormat: <?php echo $this->helper('core')->jsonEncode($this->getJsPriceFormat()) ?>,
    priceVar: '<?php echo $this->helper('bubble_layer')->getPriceRequestVar() ?>'
});
//]]>
</script>