<?php
$setting = Mage::helper('em0071settings');
?>
<link rel="stylesheet" id="emcssvariation" type="text/css" href="<?php echo $this->getSkinUrl('css/theme.css.php').'?ie=1&'.http_build_query($setting->getAllCssConfig(), '', '&amp;'); ?>"></link>
<link rel="stylesheet" id="bootstrap" type="text/css" media="all" href="<?php echo $this->getSkinUrl('bootstrap/css/bootstrap.min.css');?>"></link>

<!--[if lt IE 9]>
<script type="text/javascript">
(function() {
	var el = document.getElementById('emcssvariation');
	el.parentNode.removeChild(el);
})();
</script>
<link rel="stylesheet" id="emcssvariation" type="text/css" href="<?php echo $this->getSkinUrl('css/theme.css.php').'?ie=1&'.http_build_query($setting->getAllCssConfig(), '', '&amp;'); ?>"></link>
<![endif]-->

<!--[if lt IE 9]>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/fixiebootrap.js')?>"></script>
<![endif]-->

<!--[if lt IE 8]>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/fixiebootrap.js')?>"></script>
<![endif]-->

<?php if ($setting->getTypography_GoogleFonts()): ?>
<script type="text/javascript">
  WebFontConfig = {
    google: { families: <?php echo Zend_Json::encode(explode(',', $setting->getTypography_GoogleFonts())) ?> }
  };
  (function() {
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
        '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
  })();
</script>
<?php endif ?>

<script type="text/javascript">
//<![CDATA[
EM_Theme = {
    AJAXCART_AUTOCLOSE: <?php echo $setting->getAjaxcart_AutoClose(0) ?>,
	FREEZED_TOP_MENU: <?php echo $setting->getGeneral_FreezedTopMenu(0) ?>
};
//]]>
</script>

<style type="text/css">
<?php echo $setting->getTypography_CustomCss(); ?>
</style>

<script type="text/javascript">
//<![CDATA[
var urlSkinsite = '<?php echo $this->getSKinUrl(); ?>';
LightboxOptions = Object.extend({
    fileLoadingImage:        urlSkinsite+'images/loading.gif',     
    fileBottomNavCloseImage: urlSkinsite+'images/closelabel.gif',

    overlayOpacity: 0.8,   // controls transparency of shadow overlay

    animate: true,         // toggles resizing animations
    resizeSpeed: 7,        // controls the speed of the image resizing animations (1=slowest and 10=fastest)

    borderSize: 10,         //if you adjust the padding in the CSS, you will need to update this variable

	// When grouping images this is used to write: Image # of #.
	// Change it for non-english localization
	labelImage: "Image",
	labelOf: "of"
}, window.LightboxOptions || {});
//]]>
</script>
