<?php
/**
 * @category    Bubble
 * @package     Bubble_Search
 * @version     1.2.1
 * @copyright   Copyright (c) 2014 BubbleCode (http://www.bubbleshop.net)
 *
 * @var $this Bubble_Search_Block_Catalogsearch_Suggest
 */
$suggestion = $this->getSuggestion();
?>
<?php if (!empty($suggestion)): ?>
    <h2><em><?php echo $this->__('Did you mean %s?', '<a href="'. $this->getQueryUrl($suggestion) .'">'. $suggestion .'</a>'); ?></em></h2>
<?php endif; ?>